services:
  ml:
    restart: always
    environment:
      _UVICORN_HOST: "0.0.0.0"
      _UVICORN_PORT: 8000

    ports:
      - "8001:8000"

    build:
      context: ./ml
      dockerfile: Dockerfile
    depends_on:
      - search
    volumes:
      - ./ml:/app
      - ./secrets/ml.env:/app/.env
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 10000M

  search:
    build:
      context: ./search
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./search:/app
      - ./secrets/search.json:/app/config.json
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2000M
