services:
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: ./app
    environment:
      - PORT=3000
      - ORIGIN=http://87.242.103.101

    env_file:
      - ./secrets/app.env
    volumes:
      - ./static:/app/static
    ports:
      - 80:3000

  redis:
    container_name: redis
    image: redis:7.2.3-bookworm
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./volumes/redis/:/data
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 4G

  ml:
    container_name: ml
    restart: unless-stopped
    env_file:
      - ./secrets/ml.env
    ports:
      - "8001:8000"
    build:
      context: ./ml
      dockerfile: Dockerfile
    depends_on:
      - search
      - chroma
      - redis
    volumes:
      - ./ml/:/app/
      - ./secrets/ml.env:/app/.env
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: 10G

  chroma:
    container_name: chromadb
    restart: unless-stopped
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
      - CHROMA_HOST_PORT=8000
    volumes:
      - ./volumes/chroma_index_data:/chroma/.chroma/index
    ports:
      - 8003:8000
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 4G

  search:
    restart: unless-stopped
    build:
      context: ./search
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./search/:/app/
      - ./secrets/search.json:/app/config.json
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 2G

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:7000

volumes:
  db:
    driver: local
