repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: check-ast
          - id: check-toml
          - id: check-json
          - id: check-xml
          - id: name-tests-test
            args: ["--pytest-test-first"]
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.4.9
      hooks:
        - id: ruff
          types_or: [python, pyi, jupyter]
          args: [ --fix, --exit-non-zero-on-fix ]
